version=0.0.1
repository=113284361828.dkr.ecr.us-east-2.amazonaws.com/aicoe/mcp-context7-service
container=mcp-context7-service-container
ecs_cluster=ccoe-devops-aicoe-poc
ecs_service=mcp-context7-service
ecs_service_desired_count=1
subnet_ids=subnet-079d47eac0ec553aa,subnet-0d220ebc6169095b8
security_group_ids=sg-0dd2ea27864c7af6d
